# Generated by Django 5.2 on 2025-04-03 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('order_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('order_date', models.DateField()),
                ('customer_name', models.CharField(max_length=100)),
                ('ordertype', models.CharField(choices=[('Video', 'Video'), ('Graphics', 'Graphics'), ('Web', 'Web'), ('Thumbnail', 'Thumbnail'), ('digital marketting', 'digital marketing'), ('Social media management', 'Social media management')], default='Video', max_length=100)),
            ],
        ),
    ]
