# Generated by Django 5.2 on 2025-04-15 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstpage', '0004_contact_us'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact_us',
            old_name='full Name',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='contact_us',
            old_name='phone number',
            new_name='phone_number',
        ),
    ]
